Vagrant.configure("2") do |c|
  c.ssh.insert_key = false

  c.vm.define "provisioner" do |ne|
    ne.vm.box = "opscode-ubuntu-14.04"
    ne.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box"
    ne.vm.hostname = "target.vagrantup.com"
    ne.vm.synced_folder "../../.", "/vagrant"
    ne.vm.network(:private_network, {:ip=>"192.168.33.171"})
    ne.vm.provider :virtualbox do |p|
      p.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  c.vm.define "ssh-one" do |one|
    one.vm.box = "opscode-ubuntu-14.04"
    one.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box"
    one.vm.hostname = "target01.vagrantup.com"
    one.vm.synced_folder ".", "/vagrant", disabled: true
    one.vm.network(:private_network, {:ip=>"192.168.33.122"})
    one.vm.provider :virtualbox do |p|
      p.customize ["modifyvm", :id, "--memory", "256"]
    end
  end

  c.vm.define "ssh-two" do |two|
    two.vm.box = "opscode-ubuntu-14.04"
    two.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box"
    two.vm.hostname = "target02.vagrantup.com"
    two.vm.synced_folder ".", "/vagrant"
    two.vm.network(:private_network, {:ip=>"192.168.33.123"})
    two.vm.provider :virtualbox do |p|
      p.customize ["modifyvm", :id, "--memory", "256"]
    end
  end

  c.vm.define "ssh-three" do |three|
    three.vm.box = "opscode-ubuntu-14.04"
    three.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box"
    three.vm.hostname = "target03.vagrantup.com"
    three.vm.synced_folder ".", "/vagrant"
    three.vm.network(:private_network, {:ip=>"192.168.33.124"})
    three.vm.provider :virtualbox do |p|
      p.customize ["modifyvm", :id, "--memory", "256"]
    end
  end
end
